data_owner:
  verbose: False
  plaintext_dir: data_owner/plaintexts/D10  # used in the indexing algorithm
  add_file: data_owner/plaintexts/D10_A/12.txt  # used in file insertion algorithm
  delete_file: cloud_service_provider/ciphertexts/D10/2e.txt  # used in the delete algorithm

trusted_authority:
  verbose: False

cloud_service_provider:
  verbose: False

search_user:
  verbose: False
