data_owner:
  verbose: False
  plaintext_dir: data_owner/plaintexts/D25  # used in the indexing algorithm
  add_file: data_owner/plaintexts/D25_A/27.txt  # used in file insertion algorithm
  delete_file: cloud_service_provider/ciphertexts/D25/2.txt  # used in the delete algorithm

trusted_authority:
  verbose: False

cloud_service_provider:
  verbose: False

search_user:
  verbose: False
